BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role,email_address) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER','user@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN', 'admin@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('manager','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'manager@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Philippe','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'P.Billeaudeaux@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Steve','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'S.Riley@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Tony','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'T.Dagradi@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Kevin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'K.Griffin@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Joe','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'J.Gelini@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Dan','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'D.Cutler@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Eric','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'E.Belletto@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Mario','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'M.Palmisano@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('Justin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'J.Aliperti@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('George','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_MANAGER', 'G.Porter@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('userTest1','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER','testingUser1@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('userTest2','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER','testingUser2@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('userTest3','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER','testingUser3@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('userTest4','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER','testingUser4@gmail.com');
INSERT INTO users (username,password_hash,role,email_address) VALUES ('userTest5','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER','testingUser5@gmail.com');


INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('Feufollet', 'Feufollet is an Americana/Cajun band from Lafayette, Louisiana.', 'Philippe Billeaudeaux, Kelli Jones-Savoy, Chris Segura, Chris Stafford, Mike Stafford, Andrew Toups', 'https://tinyurl.com/5n94mkfx', (select user_id from users where email_address = 'P.Billeaudeaux@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('Steve Riley and the Mamou Playboys', 'Steve Riley and the Mamou Playboys are an American Cajun band from southern Louisiana. The band formed in 1988 and has since recorded 10 albums, nine of which are on Rounder Records.', 'Steve Riley, Sam Broussard, Brazos Huval, Kevin Dugas, Kevin Wimmer', 'https://tinyurl.com/2mtdf2bs', (select user_id from users where email_address = 'S.Riley@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('Astral Project', 'Astral Project is a modern jazz quartet from New Orleans, Louisiana. It was founded by saxophonist Tony Dagradi in 1978 and includes drummer Johnny Vidacovich, bassist James Singleton and 7-string guitarist Steve Masakowski.', 'Tony Dagradi, Johnny Vidacovich, James Singleton, Steve Masakowski', 'https://tinyurl.com/35mawexc', (select user_id from users where email_address = 'T.Dagradi@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('Better Than Ezra', 'Better Than Ezra is an American alternative rock band based in New Orleans, Louisiana, and signed with The End Records.', 'Kevin Griffin, Tom Drummond, James Arthur Payne Jr., Michael Jerome', 'https://tinyurl.com/2rnfdm4d', (select user_id from users where email_address = 'K.Griffin@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('Cha Wa', 'Cha Wa is a Grammy-nominated Mardi Gras Indian funk band based out of New Orleans, Louisiana. The name Cha Wa is a slang phrase used by Mardi Gras Indian tribes, meaning "here we come."', 'Joe Gelini, Honey Banister', 'https://tinyurl.com/25wj2vvx', (select user_id from users where email_address = 'J.Gelini@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('The Deslondes', 'The Deslondes are an Americana musical group from New Orleans, Louisiana. Their music blends together influences from folk, rock and roll, bluegrass, R&B, American roots music, blues, gospel, country, and zydeco.', 'Dan Cutler, Sam Doores, Riley Downing, Cameron Snyder, John James Tourville', 'https://tinyurl.com/2p86cxc9', (select user_id from users where email_address = 'D.Cutler@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('Egg Yolk Jubilee', 'Egg Yolk Jubilee is a band based in New Orleans and noted for their eclectic musical style, combining jazz, blues, funk, and rock elements. In addition to traditional stage venues, they also perform as a street-walking brass band, and have released several studio albums.', 'Eric Belletto, Paul Grass, Keith Hajjar, Mike Hogan, Mac McCann, Glenn Grass', 'https://tinyurl.com/ytws933j', (select user_id from users where email_address = 'E.Belletto@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('Flow Tribe', 'Flow Tribe is an American funk rock band based in New Orleans, Louisiana. The group contains six members who are all natives of New Orleans. The band was founded in 2004, and was featured on Episode 11 of MTVs The Real World: New Orleans, which aired September 8, 2010.', 'K.C. O''Rorke, John-Michael Early, Russell Olschner, Chad Penot, Bryan Santos, Mario Palmisano', 'https://tinyurl.com/yeyjjkjk', (select user_id from users where email_address = 'M.Palmisano@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('Groovesect', 'Groovesect was founded in 2006 by New Orleans musicians who had played together in various incarnations since they were eighteen, blending syncopated funk beats and jazz rhythms with rock and soul. Since "Uganda" joined the band in the spring of 2007, Groovesect has been voted the #1 Funk Band and #2 Contemporary Jazz Band in the 2007 Best of the Big Easy Awards.', 'Danny Abel, Nick Krawitz, Tim Sullivan, Eric Vogel, Colin Davis, Alfred Uganda" Roberts, Justin Aliperti', 'https://tinyurl.com/4uy3h3nf', (select user_id from users where email_address = 'J.Aliperti@gmail.com'));
INSERT INTO band (band_name, band_description, band_member, band_image, manager_id) VALUES ('The Meters', 'The Meters are an American funk band formed in 1965 in New Orleans by Zigaboo Modeliste (drums), George Porter Jr. (bass), Leo Nocentelli (guitar) and Art Neville (keyboards). The band performed and recorded their own music from the late 1960s until 1977 and played an influential role as backing musicians for other artists.', 'George Porter Jr., Leo Nocentelli, Zigaboo Modeliste, Brian Stoltz, Terrence Houston', 'https://tinyurl.com/yc63n7rk', (select user_id from users where email_address = 'G.Porter@gmail.com'));

INSERT INTO genre (genre_name) VALUES ('Jazz');
INSERT INTO genre (genre_name) VALUES ('Folk');
INSERT INTO genre (genre_name) VALUES ('Bluegrass');
INSERT INTO genre (genre_name) VALUES ('Rock');
INSERT INTO genre (genre_name) VALUES ('Country');
INSERT INTO genre (genre_name) VALUES ('Americana');
INSERT INTO genre (genre_name) VALUES ('Cajun');
INSERT INTO genre (genre_name) VALUES ('Blues');
INSERT INTO genre (genre_name) VALUES ('Gospel');
INSERT INTO genre (genre_name) VALUES ('R&B');
INSERT INTO genre (genre_name) VALUES ('Zydeco');
INSERT INTO genre (genre_name) VALUES ('Funk');
INSERT INTO genre (genre_name) VALUES ('Soul');

INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Feufollet'), (select genre_id from genre where genre_name = 'Americana'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Feufollet'), (select genre_id from genre where genre_name = 'Cajun'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Steve Riley and the Mamou Playboys'), (select genre_id from genre where genre_name = 'Cajun'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Astral Project'), (select genre_id from genre where genre_name = 'Jazz'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Better Than Ezra'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Cha Wa'), (select genre_id from genre where genre_name = 'Funk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Americana'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Folk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Bluegrass'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'R&B'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Blues'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Gospel'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Country'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Deslondes'), (select genre_id from genre where genre_name = 'Zydeco'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Egg Yolk Jubilee'), (select genre_id from genre where genre_name = 'Jazz'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Egg Yolk Jubilee'), (select genre_id from genre where genre_name = 'Blues'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Egg Yolk Jubilee'), (select genre_id from genre where genre_name = 'Folk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Egg Yolk Jubilee'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Flow Tribe'), (select genre_id from genre where genre_name = 'Funk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Flow Tribe'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Groovesect'), (select genre_id from genre where genre_name = 'Funk'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Groovesect'), (select genre_id from genre where genre_name = 'Jazz'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Groovesect'), (select genre_id from genre where genre_name = 'Rock'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'Groovesect'), (select genre_id from genre where genre_name = 'Soul'));
INSERT INTO band_genre (band_id, genre_id) VALUES ((select band_id from band where band_name = 'The Meters'), (select genre_id from genre where genre_name = 'Funk'));

INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Feufollet'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Steve Riley and the Mamou Playboys'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Astral Project'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Better Than Ezra'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Cha Wa'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'The Deslondes'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Egg Yolk Jubilee'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Flow Tribe'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'Groovesect'));
INSERT INTO messages (message_body, message_timestamp, band_id) VALUES ('Hey everyone, our new fan band page is up and running!', CURRENT_TIMESTAMP, (select band_id from band where band_name = 'The Meters'));

INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('House of Blues', '225 Decatur St, New Orleans, LA 70130', 'Rock & blues-themed chain with Southern dishes such as po boys & jambalaya, plus live music.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ9cCHcw2mIIYRV7dOHIoKO4Q&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('Preservation Hall', '726 St Peter, New Orleans, LA 70116', 'Historic, all-ages place for jazz in a no-frills space with wooden floors & no air-conditioning.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJb2JeIA6mIIYRXpHm7_QGZjM&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('Gasa Gasa', '4920 Freret St, New Orleans, LA 70115', 'Gasa Gasa is the uptown neighborhood''s newest music and arts venue. Located on Feret Street, Gasa Gasa supports local talent through weekly events.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ4_JiSKmlIIYRTkZm4D0v1zA&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('The Howlin'' Wolf', '907 S Peters St, New Orleans, LA 70130', 'Musical acts shine at this expansive, low-key concert hall with a mahogany bar & pub fare.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJSYn2znGmIIYRmCUMqQhZ_Zc&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('d.b.a.', '618 Frenchmen St, New Orleans, LA 70116', 'Popular, intimate nightspot pouring craft beers & hosting an eclectic lineup of live music.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJsQz8SRimIIYREARKIRAffaU&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('Fillmore New Orleans', '6 Canal St, New Orleans, LA 70130', 'The Fillmore was the focal point for the psychedelic music scene during the 1960s and 1970s, helping launch the careers of the biggest names of the era such as The Grateful Dead, Jimi Hendrix, Led Zeppelin, and The Doors.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJSQBCQW2mIIYRAkwTxKE9zQk&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('Tipitina''s', '501 Napoleon Ave, New Orleans, LA 70115', 'Rustic, black-and-white tiled warehouse space & landmark since ’77 for live music & Cajun dancing.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ7Q8OmU-kIIYR6f0q4VwM-Ik&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('Three Keys At Ace Hotel New Orleans', '600 Carondelet St, New Orleans, LA 70130', 'Cocktails and casual eats in the lobby makes for great people watching. Reasonably priced and conveniently located in the CBD.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJHdxs-XSmIIYRKBmpbJoSajI&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('Republic NOLA', '828 S Peters St, New Orleans, LA 70130', 'Warehouse turned concert venue & club (Thursdays–Saturdays) with wooden beams & crystal chandeliers.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJJ9Zs5HGmIIYRldJ5SKhZC90&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');
INSERT INTO venue (venue_name, venue_address, venue_description, venue_map) VALUES ('Blue Nile', '532 Frenchmen St, New Orleans, LA 70116', 'A range of acts from funk & blues to brass bands takes the stage at this longtime live music bar.', 'https://www.google.com/maps/embed/v1/place?q=place_id:ChIJG9jTLximIIYRJY38eNhc040&key=AIzaSyBRq0tBrXJcI2Tff8JxVYGmR58CimOPI7o');

INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 06:00:00', (select venue_id from venue where venue_name = 'House of Blues'), 'The amazing show at House of Blues!', 'Come down to the House of Blues and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 06:00:00', (select venue_id from venue where venue_name = 'd.b.a.'), 'The amazing show at d.b.a!', 'Come down to d.b.a and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 06:30:00', (select venue_id from venue where venue_name = 'Blue Nile'), 'The amazing show at Blue Nile!', 'Come down to Blue Nile and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 06:30:00', (select venue_id from venue where venue_name = 'Preservation Hall'), 'The amazing show at Preservation Hall!', 'Come down to Preservation Hall and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 07:00:00', (select venue_id from venue where venue_name = 'Republic NOLA'), 'The amazing show at Republic NOLA!', 'Come down to Republic NOLA and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 07:00:00', (select venue_id from venue where venue_name = 'Gasa Gasa'), 'The amazing show at Gasa Gasa!', 'Come down to Gasa Gasa and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 07:30:00', (select venue_id from venue where venue_name = 'Three Keys At Ace Hotel New Orleans'), 'The amazing show at Three Keys!', 'Come down to Three Keys and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 07:30:00', (select venue_id from venue where venue_name = 'The Howlin'' Wolf'), 'The amazing show at The Howlin'' Wolf', 'Come down to The Howlin'' Wolf and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 08:00:00', (select venue_id from venue where venue_name = 'Tipitina''s'), 'The amazing show at Tipitina''s!', 'Come down to Tipitina''s and watch some live music!');
INSERT INTO show (show_time, venue_id, show_title, show_description) VALUES (timestamp '2022-08-12 08:00:00', (select venue_id from venue where venue_name = 'Fillmore New Orleans'), 'The amazing show at Fillmore New Orleans', 'Come down to the Fillmore New Orleans and watch some live music!');

INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 06:00:00' and venue_id = (select venue_id from venue where venue_name = 'House of Blues')), (select band_id from band where band_name = 'The Meters'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 06:00:00' and venue_id = (select venue_id from venue where venue_name = 'House of Blues')), (select band_id from band where band_name = 'Feufollet'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 06:00:00' and venue_id = (select venue_id from venue where venue_name = 'House of Blues')), (select band_id from band where band_name = 'Steve Riley and the Mamou Playboys'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 06:00:00' and venue_id = (select venue_id from venue where venue_name = 'd.b.a.')), (select band_id from band where band_name = 'Groovesect'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 06:30:00' and venue_id = (select venue_id from venue where venue_name = 'Preservation Hall')), (select band_id from band where band_name = 'Flow Tribe'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 06:30:00' and venue_id = (select venue_id from venue where venue_name = 'Blue Nile')), (select band_id from band where band_name = 'Egg Yolk Jubilee'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 07:00:00' and venue_id = (select venue_id from venue where venue_name = 'Republic NOLA')), (select band_id from band where band_name = 'The Deslondes'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 07:00:00' and venue_id = (select venue_id from venue where venue_name = 'Gasa Gasa')), (select band_id from band where band_name = 'Cha Wa'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 07:30:00' and venue_id = (select venue_id from venue where venue_name = 'The Howlin'' Wolf')), (select band_id from band where band_name = 'Better Than Ezra'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 07:30:00' and venue_id = (select venue_id from venue where venue_name = 'Three Keys At Ace Hotel New Orleans')), (select band_id from band where band_name = 'Astral Project'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 08:00:00' and venue_id = (select venue_id from venue where venue_name = 'Tipitina''s')), (select band_id from band where band_name = 'Steve Riley and the Mamou Playboys'));
INSERT INTO show_band (show_id, band_id) VALUES ((select show_id from show where show_time = '2022-08-12 08:00:00' and venue_id = (select venue_id from venue where venue_name = 'Fillmore New Orleans')), (select band_id from band where band_name = 'Feufollet'));

INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'George'), (select band_id from band where band_name = 'The Meters'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Philippe'), (select band_id from band where band_name = 'Feufollet'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Steve'), (select band_id from band where band_name = 'Steve Riley and the Mamou Playboys'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Justin'), (select band_id from band where band_name = 'Groovesect'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Mario'), (select band_id from band where band_name = 'Flow Tribe'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Eric'), (select band_id from band where band_name = 'Egg Yolk Jubilee'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Dan'), (select band_id from band where band_name = 'The Deslondes'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Joe'), (select band_id from band where band_name = 'Cha Wa'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Kevin'), (select band_id from band where band_name = 'Better Than Ezra'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'Tony'), (select band_id from band where band_name = 'Astral Project'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'The Meters'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'Feufollet'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'Steve Riley and the Mamou Playboys'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'Groovesect'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'Flow Tribe'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'Egg Yolk Jubilee'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'The Deslondes'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'Cha Wa'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'Better Than Ezra'));
INSERT INTO user_band (user_id, band_id) VALUES ((select user_id from users where username = 'user'), (select band_id from band where band_name = 'Astral Project'));

INSERT INTO user_messages (user_id, message_id) VALUES ('1', '1');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '2');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '3');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '4');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '5');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '6');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '7');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '8');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '9');
INSERT INTO user_messages (user_id, message_id) VALUES ('1', '10');
INSERT INTO user_messages (user_id, message_id) VALUES ('4', '1');
INSERT INTO user_messages (user_id, message_id) VALUES ('5', '2');
INSERT INTO user_messages (user_id, message_id) VALUES ('6', '3');
INSERT INTO user_messages (user_id, message_id) VALUES ('7', '4');
INSERT INTO user_messages (user_id, message_id) VALUES ('8', '5');
INSERT INTO user_messages (user_id, message_id) VALUES ('9', '6');
INSERT INTO user_messages (user_id, message_id) VALUES ('10', '7');
INSERT INTO user_messages (user_id, message_id) VALUES ('11', '8');
INSERT INTO user_messages (user_id, message_id) VALUES ('12', '9');
INSERT INTO user_messages (user_id, message_id) VALUES ('13', '10');

INSERT INTO photo (photo_url) VALUES ('https://tinyurl.com/4z95wpvu');
INSERT INTO photo (photo_url) VALUES ('https://tinyurl.com/5n7mj2dj');
INSERT INTO photo (photo_url) VALUES ('https://tinyurl.com/4c3jx2ew');
INSERT INTO photo (photo_url) VALUES ('https://tinyurl.com/yc379892');
INSERT INTO photo (photo_url) VALUES ('https://tinyurl.com/yk6jdc44');

INSERT INTO band_photo VALUES ('1', '1');
INSERT INTO band_photo VALUES ('1', '2');
INSERT INTO band_photo VALUES ('1', '3');
INSERT INTO band_photo VALUES ('1', '4');
INSERT INTO band_photo VALUES ('1', '5');
INSERT INTO band_photo VALUES ('2', '1');
INSERT INTO band_photo VALUES ('2', '2');
INSERT INTO band_photo VALUES ('2', '3');
INSERT INTO band_photo VALUES ('2', '4');
INSERT INTO band_photo VALUES ('2', '5');

COMMIT TRANSACTION;
